# Generated by Django 5.1.3 on 2024-12-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, verbose_name='角色描述')),
                ('created_at', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '角色',
                'db_table': 'bangtuitui_py_shop_role',
            },
        ),
        migrations.CreateModel(
            name='RoleAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField()),
                ('access_id', models.IntegerField()),
                ('created_at', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '角色权限关联',
                'db_table': 'bangtuitui_py_shop_role_access',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_user_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
                ('create_time', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '用户角色关联',
                'db_table': 'bangtuitui_py_shop_user_role',
            },
        ),
    ]
