# Generated by Django 5.1.3 on 2024-12-01 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denglu', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='bangtuitui_py_shop_user',
        ),
    ]
